FROM ubuntu:20.04
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y apt-utils
RUN apt-get install -y python3-pip
RUN mkdir /apps
COPY ./app_a.py /apps/app_a.py
COPY ./schema.sql /apps/schema.sql
COPY ./requirements.txt /apps/requirements.txt
RUN pip3 install -r /apps/requirements.txt
EXPOSE 5000
CMD ["/usr/bin/python3", "/apps/app_a.py"]
