FROM ubuntu:20.04
RUN apt-get update -y && apt-get upgrade -y  && apt-get install -y apt-utils
RUN apt-get install -y python3-pip sqlite3
RUN mkdir /apps
COPY ./app_b.py /apps/app_b.py
COPY ./schema.sql /apps/schema.sql
COPY ./requirements.txt /apps/requirements.txt
RUN pip3 install -r /apps/requirements.txt
RUN sqlite3 /apps/database.db < /apps/schema.sql
EXPOSE 5001
CMD ["/usr/bin/python3", "/apps/app_b.py"]
